import type { Metadata } from "next";
import "./globals.css";
import I18nProvider from "../lib/providers/I18nProvider";
import AppBar from "@/components/app/app-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <I18nProvider>
      <html lang="en">
        <head>
          <script
            src="https://kit.fontawesome.com/023ee49cbe.js"
            crossOrigin="anonymous"
          ></script>
        </head>
        <body className="max-w-lg min-h-screen m-auto">
          {children}
          <AppBar />
        </body>
      </html>
    </I18nProvider>
  );
}
