import type { Metadata } from "next";
import "./globals.css";
import I18nProvider from "../lib/providers/I18nProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <I18nProvider>
      <html lang="en">
        <body className="max-w-lg min-h-screen m-auto">{children}</body>
      </html>
    </I18nProvider>
  );
}
